In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('Titanic-Dataset.csv')

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [5]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [6]:

df.groupby(['Pclass', 'Sex'])['Survived'].mean()

Pclass  Sex
1       female    0.968085
        male      0.368852
2       female    0.921053
        male      0.157407
3       female    0.500000
        male      0.135447
Name: Survived, dtype: float64

In [7]:
df['IsWoman']=(df['Sex']=='female').astype(int)

In [8]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,IsWoman
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0

In [9]:
df['FamilySize']=df['SibSp']+df['Parch']+1

In [10]:
df.groupby(['Pclass', 'IsWoman'])['Survived'].mean()

Pclass  IsWoman
1       0          0.368852
        1          0.968085
2       0          0.157407
        1          0.921053
3       0          0.135447
        1          0.500000
Name: Survived, dtype: float64

In [11]:
df.groupby('Cabin')['Survived'].mean()

Cabin
A10    0.0
A14    0.0
A16    1.0
A19    0.0
A20    1.0
      ...
F33    1.0
F38    0.0
F4     1.0
G6     0.5
T      0.0
Name: Survived, Length: 147, dtype: float64

We can come back to this later find out how this played a role in survival, also need to clean it up and see which cabins had better access to lifeboats

In [12]:
df.groupby(['FamilySize'])['Survived'].mean()

FamilySize
1     0.303538
2     0.552795
3     0.578431
4     0.724138
5     0.200000
6     0.136364
7     0.333333
8     0.000000
11    0.000000
Name: Survived, dtype: float64

We can come back to this later find out how this played a role in survival

In [13]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,IsWoman,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0,1

In [14]:
df['FarePP']=df['Fare']/df['FamilySize']

In [15]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,IsWoman,FamilySize,FarePP
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,2,3.62500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1,2,35.64165
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,1,7.92500
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1,2,26.55000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0,1,8.05000

In [16]:
df['CabinLetter'] = df['Cabin'].str[0]

In [17]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,IsWoman,FamilySize,FarePP,CabinLetter
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,2,3.62500,NaN
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1,2,35.64165,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,1,7.92500,NaN
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1,2,26.55000,C
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0,1,8.05000,NaN

In [22]:
df.groupby(['Pclass'])['FarePP'].mean().sort_values(ascending=False)

Pclass
1    52.936943
2    12.698832
3     8.094756
Name: FarePP, dtype: float64

In [23]:
df.groupby(['Pclass', 'CabinLetter'])['FarePP'].mean().sort_values(ascending=False)

Pclass  CabinLetter
1       B              69.379566
        C              52.273987
        D              37.310826
        T              35.500000
        E              34.671613
        A              32.768100
2       D              13.166675
        E              11.587500
        F               9.937500
3       F               7.630553
        E               6.841667
        G               4.963021
Name: FarePP, dtype: float64

In [24]:
df.groupby(['Pclass', 'CabinLetter'], dropna=False)['FarePP'].mean().sort_values(ascending=False)

Pclass  CabinLetter
1       B              69.379566
        NaN            65.338729
        C              52.273987
        D              37.310826
        T              35.500000
        E              34.671613
        A              32.768100
2       D              13.166675
        NaN            12.845645
        E              11.587500
        F               9.937500
3       NaN             8.133602
        F               7.630553
        E               6.841667
        G               4.963021
Name: FarePP, dtype: float64

In [27]:
df.groupby(['Pclass', 'CabinLetter'], dropna=False)['FarePP'].agg(count='count',mean_fare='mean').sort_values('mean_fare', ascending=False).round(2)

                    count  mean_fare
Pclass CabinLetter
1      B               47      69.38
       NaN             40      65.34
       C               59      52.27
       D               29      37.31
       T                1      35.50
       E               25      34.67
       A               15      32.77
2      D                4      13.17
       NaN            168      12.85
       E                4      11.59
       F                8       9.94
3      NaN            479       8.13
       F                5       7.63
       E                3       6.84
       G                4       4.96

In [26]:
df.groupby('CabinLetter', dropna=False).agg(count=('Survived', 'count'),survival_rate=('Survived', 'mean'))

             count  survival_rate
CabinLetter
A               15       0.466667
B               47       0.744681
C               59       0.593220
D               33       0.757576
E               32       0.750000
F               13       0.615385
G                4       0.500000
T                1       0.000000
NaN            687       0.299854

Cant rely on NaN data as it doesnt show any relation between survial or cabinletter aside from the fact that most were from the 3rd class

In [18]:
df.groupby('CabinLetter')['Fare'].mean().sort_values(ascending=False)

CabinLetter
B    113.505764
C    100.151341
D     57.244576
E     46.026694
A     39.623887
T     35.500000
F     18.696792
G     13.581250
Name: Fare, dtype: float64

In [19]:
df.groupby('CabinLetter')['FarePP'].mean().sort_values(ascending=False)

CabinLetter
B    69.379566
C    52.273987
T    35.500000
D    34.384263
A    32.768100
E    29.177041
F     9.050213
G     4.963021
Name: FarePP, dtype: float64

FarePP is a better indicator of the fare paid by each passenger, as it takes into account the family size. The average FarePP for each CabinLetter provides a more accurate representation of the fare paid by passengers in different cabins, while the average Fare may be skewed by larger families sharing a cabin and paying a higher total fare.

In [20]:
df.groupby(['CabinLetter'])['Survived'].mean().sort_values(ascending=False)

CabinLetter
D    0.757576
E    0.750000
B    0.744681
F    0.615385
C    0.593220
G    0.500000
A    0.466667
T    0.000000
Name: Survived, dtype: float64

In [28]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,IsWoman,FamilySize,FarePP,CabinLetter
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,2,3.62500,NaN
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1,2,35.64165,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,1,7.92500,NaN
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1,2,26.55000,C
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0,1,8.05000,NaN

In [ ]:
df.groupby('Embarked').agg(
    total_count=('PassengerId', 'count'),
    survival_count=('Survived', 'sum'),
    survival_rate=('Survived', 'mean'),
    avg_class=('Pclass', 'mean'),
).round(2)

          total_count  survival_count  survival_rate  avg_class
Embarked
C                 168              93           0.55       1.89
Q                  77              30           0.39       2.91
S                 644             217           0.34       2.35

In [31]:
df.groupby(['Embarked', 'Pclass']).agg(
    count=('Survived', 'count'),
    survival_rate=('Survived', 'mean')
).round(2)

                 count  survival_rate
Embarked Pclass
C        1          85           0.69
         2          17           0.53
         3          66           0.38
Q        1           2           0.50
         2           3           0.67
         3          72           0.38
S        1         127           0.58
         2         164           0.46
         3         353           0.19

Due to lack of passengers from first and second class in Q port, we cannot draw useful conclusions 
But we can see from C and S class played a major role in survival rate

In [33]:
df.groupby(['CabinLetter', 'Pclass']).agg(
    count=('Survived', 'count'),
    total_count=('PassengerId', 'count'),
    survival_rate=('Survived', 'mean')
).round(2).sort_values('survival_rate', ascending=False)

                    count  total_count  survival_rate
CabinLetter Pclass
E           3           3            3           1.00
F           2           8            8           0.88
D           1          29           29           0.76
E           2           4            4           0.75
D           2           4            4           0.75
B           1          47           47           0.74
E           1          25           25           0.72
C           1          59           59           0.59
G           3           4            4           0.50
A           1          15           15           0.47
F           3           5            5           0.20
T           1           1            1           0.00

In [35]:
df.groupby(['CabinLetter', 'Pclass'], dropna=False).agg(
    count=('Survived', 'count'),
    total_count=('PassengerId', 'count'),
    survival_rate=('Survived', 'mean')
).round(2).sort_values('Pclass', ascending=False)

                    count  total_count  survival_rate
CabinLetter Pclass
G           3           4            4           0.50
F           3           5            5           0.20
E           3           3            3           1.00
NaN         3         479          479           0.24
D           2           4            4           0.75
E           2           4            4           0.75
F           2           8            8           0.88
NaN         2         168          168           0.44
E           1          25           25           0.72
B           1          47           47           0.74
C           1          59           59           0.59
A           1          15           15           0.47
D           1          29           29           0.76
NaN         1          40           40           0.48
T           1           1            1           0.00

Most second and third class passengers were in cabins without letters, and they had the lowest survival rates. First class passengers in cabins with letters A, B, C, D, E had higher fares and better survival rates. This suggests that cabin location and class were significant factors in survival chances.